# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.energychain.com:
    container_name: orderer0.energychain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/energychain.com/orderers/orderer0.energychain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/energychain.com/orderers/orderer0.energychain.com/tls/:/var/hyperledger/orderer/tls
        - orderer0.energychain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.prosumer.energychain.com:
    container_name: peer0.prosumer.energychain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.prosumer.energychain.com
      - CORE_PEER_ADDRESS=peer0.prosumer.energychain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.prosumer.energychain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.prosumer.energychain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.prosumer.energychain.com:7051
      - CORE_PEER_LOCALMSPID=prosumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/prosumer.energychain.com/peers/peer0.prosumer.energychain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/prosumer.energychain.com/peers/peer0.prosumer.energychain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.prosumer.energychain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.prosumer.energychain.com:
    container_name: peer1.prosumer.energychain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.prosumer.energychain.com
      - CORE_PEER_ADDRESS=peer1.prosumer.energychain.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.prosumer.energychain.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.prosumer.energychain.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.prosumer.energychain.com:7051
      - CORE_PEER_LOCALMSPID=prosumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/prosumer.energychain.com/peers/peer1.prosumer.energychain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/prosumer.energychain.com/peers/peer1.prosumer.energychain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.prosumer.energychain.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.consumer.energychain.com:
    container_name: peer0.consumer.energychain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.consumer.energychain.com
      - CORE_PEER_ADDRESS=peer0.consumer.energychain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.energychain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.energychain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.energychain.com:10051
      - CORE_PEER_LOCALMSPID=consumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.energychain.com/peers/peer0.consumer.energychain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.energychain.com/peers/peer0.consumer.energychain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.consumer.energychain.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.consumer.energychain.com:
    container_name: peer1.consumer.energychain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.consumer.energychain.com
      - CORE_PEER_ADDRESS=peer1.consumer.energychain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.consumer.energychain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.energychain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.energychain.com:9051
      - CORE_PEER_LOCALMSPID=consumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/consumer.energychain.com/peers/peer1.consumer.energychain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/consumer.energychain.com/peers/peer1.consumer.energychain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.consumer.energychain.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.exchange.energychain.com:
    container_name: peer0.exchange.energychain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exchange.energychain.com
      - CORE_PEER_ADDRESS=peer0.exchange.energychain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.exchange.energychain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exchange.energychain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.exchange.energychain.com:12051
      - CORE_PEER_LOCALMSPID=consumerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exchange.energychain.com/peers/peer0.exchange.energychain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exchange.energychain.com/peers/peer0.exchange.energychain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.exchange.energychain.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.exchange.energychain.com:
    container_name: peer1.exchange.energychain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.exchange.energychain.com
      - CORE_PEER_ADDRESS=peer1.exchange.energychain.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.exchange.energychain.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.exchange.energychain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.exchange.energychain.com:12051
      - CORE_PEER_LOCALMSPID=exchangeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exchange.energychain.com/peers/peer1.exchange.energychain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exchange.energychain.com/peers/peer1.exchange.energychain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.exchange.energychain.com:/var/hyperledger/production
    ports:
      - 12051:12051
